### ISSUE TITLE
Please rename the repo, so it doesn't conflict with the original wasm-coremark

### ISSUE THREAD

**Issue by vshymanskyy** [patractlabs/wasmi-coremark#2]
`wasmi-coremark` could be a good alternative, but it allows running in multiple engines...
Maybe `wasm-coremark-rust` or something similar?

**Comment by vshymanskyy** [comment]
@patractlabs

**Comment by clearloop** [comment]
What about `wasm-coremark-rs` @vshymanskyy ?

**Comment by vshymanskyy** [comment]
looks great!
